Update 04.01.10-FW23
Signed-off-by: Thomas Brandt <Thomas.Brandt@wago.com>

diff --git a/projectroot/etc/init.d/lighttpd b/projectroot/etc/init.d/lighttpd
--- a/projectroot/etc/init.d/lighttpd
+++ b/projectroot/etc/init.d/lighttpd
@@ -4,7 +4,7 @@
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 #
-# Copyright (c) 2011-2021 WAGO GmbH & Co. KG
+# Copyright (c) 2011-2022 WAGO GmbH & Co. KG
 #-----------------------------------------------------------------------------#
 #-----------------------------------------------------------------------------#
 # Script:   /etc/init.d/lighttpd
@@ -22,6 +22,8 @@ LIGHTTPD_CONF="/etc/lighttpd/lighttpd.conf"
 LIGHTTPD_LOGDIR="/var/log/lighttpd"
 LIGHTTPD_PHP_SESSION_DIR="/var/run/php/sessions"
 START_STOP_DAEMON="/sbin/start-stop-daemon"
+# According to setting "server.graceful-shutdown-timeout" in lighttpd.conf
+WAIT_FOR_STOP_TIMEOUT=60 
 
 # Somehow we rarly get SIGHUP signals, which can cause
 # "start" or "stop" to be interrupted unexpectedly.
@@ -106,12 +108,12 @@ wait_for_stop()
     local try_count=0
     while $START_STOP_DAEMON --stop -t --quiet --exec "${LIGHTTPD}"; do
         try_count=$((try_count+1))
-        if [[ $try_count -gt 20 ]]; then
+        if [[ $try_count -gt ${WAIT_FOR_STOP_TIMEOUT} ]]; then
             result=1
             break
         fi
         echo -n "."
-        usleep 100000
+        sleep 1
     done
     echo ""
 
@@ -186,6 +188,23 @@ case $1 in
         fi
         ;;
 
+    restart)
+        echo "${PREFIX}restart"
+        if stop; then
+            echo "${PREFIX}stop done"
+            if start; then
+                echo "${PREFIX}start done"
+                exit 0
+            else
+                echo "${PREFIX}error, could not start server" >&2
+                exit 1
+            fi
+        else
+            echo "${PREFIX}error, could not stop server" >&2
+            exit 1
+        fi
+        ;;
+
     reload)
         echo "${PREFIX}reload"
         if reload; then
@@ -198,7 +217,7 @@ case $1 in
         ;;
 
     *)
-        echo "${PREFIX}usage: ${0} [start|stop|status|reload]" >&2
+        echo "${PREFIX}usage: ${0} [start|stop|status|restart|reload]" >&2
         exit 1
         ;;
 
